# Generated by Django 4.1.1 on 2022-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_barang', models.CharField(blank=True, max_length=200, null=True)),
                ('kategori_barang', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_barang', models.IntegerField(blank=True, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_barang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.CharField(blank=True, max_length=200, null=True)),
                ('gender_pelanggan', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat_pelanggan', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_pelanggan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id_pembelian', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_barang_pembelian', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_pembelian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id_penjualan', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaksi', models.CharField(blank=True, max_length=50, null=True)),
                ('jumlah_barang', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_penjualan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat_supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('is_superuser', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
