# Generated by Django 4.1.1 on 2022-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiGenerateModel',
            fields=[
                ('id_absensi', models.AutoField(primary_key=True, serialize=False)),
                ('id_agenda', models.IntegerField(blank=True, null=True)),
                ('id_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_absensi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AbsensiModel',
            fields=[
                ('id_absensi', models.AutoField(primary_key=True, serialize=False)),
                ('status_absensi', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_absensi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaModel',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('nama_agenda', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi_agenda', models.TextField(blank=True, null=True)),
                ('tanggal_agenda', models.DateTimeField(blank=True, null=True)),
                ('hasil_agenda', models.CharField(blank=True, max_length=200, null=True)),
                ('id_user_created', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JenisAgendaModel',
            fields=[
                ('id_jenis_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis_agenda', models.CharField(blank=True, max_length=200, null=True)),
                ('id_user_created', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_jenis_agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LpjModel',
            fields=[
                ('id_lpj', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lpj', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi_lpj', models.TextField(blank=True, null=True)),
                ('tanggal_lpj', models.DateTimeField(blank=True, null=True)),
                ('id_user_created', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_lpj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateAbsensiModel',
            fields=[
                ('id_absensi', models.AutoField(primary_key=True, serialize=False)),
                ('status_absensi', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_absensi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRekapAbsensi',
            fields=[
                ('id_user_rekap', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_agenda', models.DateTimeField(blank=True, null=True)),
                ('nama_agenda', models.CharField(blank=True, max_length=200, null=True)),
                ('status_absensi', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
